### ISSUE TITLE
Collecting metadata without moving files?

### ISSUE THREAD

**Issue by BrianZbr** [puhoy/lspace#24]
This looks like an awesome tool but I haven't tried it because I don't want it to move or rename any files. Is there currently an easy way to turn that part off?

**Comment by puhoy** [comment]
Hey! The default import behavior is to copy (not move) the file into your library folder, so unless you import with the `--move` switch, it will not change your source files.

**Comment by puhoy** [comment]
I think i understood, and it sounds like such a feature would make sense.
To be honest, its been three years since i last worked on this project, and im not super familiar with it anymore, but i tried to add a new flag `--inplace`, which does exactly that - it resoves the metadata as usual, but wont copy or move the file, and instead add it to your library as an "external" file.
Im not sure if there are implications i dont see yet, but importing and listing works as i would expect.

Can you try and install with `pip install git+https://github.com/puhoy/lspace.git@feature/inplaceImports` (maybe uninstall the old package before) and let me know if that works for you?

**Comment by BrianZbr** [comment]
Awesome, thanks! 

The only bug I noticed is that the download button in the web interface fails with `[Errno 2] No such file or directory: '/home/myuser/.local/lib/python3.8/site-packages/lspace/myfile.pdf'`. I'm happy to test a fix if you like, or we can just consider this closed.

**Comment by puhoy** [comment]
Strange, thats not a problem here, the download button works for internal and external files.
Maybe update and try to start the web interface with `LSPACE_DEV=1 lspace web` to enable debug logs - i just added a log which should print the file path used to serve the file, and see if that looks strange. It should be the absolute path to the file.

**Comment by BrianZbr** [comment]
When I check `book.full_path` with the debugger, it just shows the filename and not the full path. The variable `path` is indeed showing along the lines of `'/home/{myuser}/.local/lib/python3.8/site-packages/lspace/{myfile}` plus the filename, as in the original error message.

**Comment by puhoy** [comment]
Okay, after poking a bit i could reproduce this.
The problem was that i didnt resolve the absolute path when importing, which was no problem when we copied the file to the library, but of course it is when you need that exact same path later. (And i only tested with paths like `~/somewhere/...`, which the shell expands, making it an absolute path...)
Anyway, should be fixed, and i also added a check in `remove` which asks if it should delete the file or just the metadata if its an external file.

I hope you did not import a lot of stuff yet - those paths would now all be relative to where you imported from... 
Let me know if it works for you now (after update and re-import)!

**Comment by BrianZbr** [comment]
Confirmed, thanks again!

**Comment by puhoy** [comment]
Nice, thanks for testing and the suggestion!
Feel free to open an issue or a pr if you notice something weird!
